import Head from 'next/head'
import Image from 'next/image'
// import Script from 'next/script'
// import { Inter } from '@next/font/google'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Zone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <style jsx>
        {`
          .heading{
            font-size: 6rem;
            font-weight:bold;
            text-align:center;
            margin-top:12px;
            background: -webkit-linear-gradient(white, white);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-shadow: 1px 3px blue;
          }
        `}
      </style>

      <main>
        <div>
          <div className="relative">
            <img className='mx-4 -z-50' src="/coding.jpg" />
            <h1 className="absolute text-white heading top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2">
              Code Zone</h1>
            <div className='absolute text-2xl text-white bottom-10 left-1/2 -translate-x-1/2'>Welcome to our code zone blog website! Here, we share our insights and expertise on programming languages, tools, and frameworks.</div>
          </div>
        </div>
        {/* <div className="flex justify-center items-center my-3">
        <Image className='rounded-2xl' src="/coding.jpg" width={388} height={258} alt="image" />
        </div> */}
      </main>
    </>
  )
}
